name: 1 - Test GitHub actions

on:
  workflow_dispatch:
  push: # git push
    branch:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test run github actions
        run: echo "Hello, Test run github actions"

