name: 3 - Django Test ENV Vars

on:
  workflow_dispatch:
  push: # git push
    branch:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      # DJANGO_SECRET_KEY: not-good
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Django Secret Key
        run: |
          MY_GENERAGE_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$MY_GENERAGE_KEY" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Django Tests
        working-directory: ./src
        run: |
          python manage.py test
